-- V14: Create staff_sites and staff_site_applications for internal staff

-- 内部人员已加入的地盘
CREATE TABLE IF NOT EXISTS staff_sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    is_current BOOLEAN DEFAULT FALSE,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, site_id)
);

CREATE INDEX IF NOT EXISTS idx_staff_sites_user ON staff_sites(user_id);
CREATE INDEX IF NOT EXISTS idx_staff_sites_site ON staff_sites(site_id);

-- 内部人员申请加入地盘的审批记录
CREATE TABLE IF NOT EXISTS staff_site_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    site_id BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_staff_applications_user ON staff_site_applications(user_id);
CREATE INDEX IF NOT EXISTS idx_staff_applications_site ON staff_site_applications(site_id);
CREATE INDEX IF NOT EXISTS idx_staff_applications_status ON staff_site_applications(status);
