-- 远东工友App 初始数据库结构
-- V1__init_schema.sql (PostgreSQL)
-- 数据库: fareast_worker

-- Users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(255),
    name VARCHAR(100),
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    avatar VARCHAR(500),
    last_login_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Worker profiles
CREATE TABLE worker_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    hkid VARCHAR(50),
    safety_card VARCHAR(50),
    worker_registration_num VARCHAR(50),
    daily_wage DECIMAL(10,2),
    contract_attachment VARCHAR(500),
    face_registered BOOLEAN DEFAULT FALSE,
    face_image_url VARCHAR(500),
    worker_number VARCHAR(50) UNIQUE,
    safety_score INT DEFAULT 100,
    blacklisted BOOLEAN DEFAULT FALSE,
    blacklist_reason VARCHAR(500),
    card_locked BOOLEAN DEFAULT FALSE,
    current_site_id BIGINT,
    current_company_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_worker_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Companies
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(500),
    contact_person VARCHAR(100),
    contact_phone VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sites
CREATE TABLE sites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(500),
    company_id BIGINT,
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    manager_name VARCHAR(100),
    manager_phone VARCHAR(20),
    bluetooth_beacon_id VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_site_company FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- Attendances
CREATE TABLE attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    site_id BIGINT,
    check_in_time TIMESTAMP NOT NULL,
    check_out_time TIMESTAMP,
    check_in_type VARCHAR(20),
    date DATE NOT NULL,
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    location_address VARCHAR(500)
);
CREATE INDEX idx_attendance_worker_date ON attendances(worker_id, date);
CREATE INDEX idx_attendance_site_date ON attendances(site_id, date);

-- Safety videos
CREATE TABLE safety_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    video_url VARCHAR(500),
    duration INT,
    qr_code_url VARCHAR(500),
    mandatory BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Worker video views
CREATE TABLE worker_video_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,
    viewed_at TIMESTAMP,
    watched_duration INT DEFAULT 0,
    completed BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_worker_video UNIQUE (worker_id, video_id)
);

-- Blacklist records
CREATE TABLE blacklist_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    reason VARCHAR(500),
    added_by BIGINT,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    removed_at TIMESTAMP,
    removed_by BIGINT
);

-- Safety deductions
CREATE TABLE safety_deductions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    points INT NOT NULL,
    reason VARCHAR(500),
    deducted_by BIGINT,
    deducted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Site change requests
CREATE TABLE site_change_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    from_site_id BIGINT,
    to_site_id BIGINT,
    reason VARCHAR(500),
    status VARCHAR(20) DEFAULT 'PENDING',
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    processed_by BIGINT,
    reject_reason VARCHAR(500)
);

-- Company change requests
CREATE TABLE company_change_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    from_company_id BIGINT,
    to_company_id BIGINT,
    reason VARCHAR(500),
    status VARCHAR(20) DEFAULT 'PENDING',
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    processed_by BIGINT,
    reject_reason VARCHAR(500)
);

-- Announcements
CREATE TABLE announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    target_role VARCHAR(20),
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- System configs
CREATE TABLE system_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) UNIQUE NOT NULL,
    config_value TEXT,
    description VARCHAR(500)
);

-- Material requests
CREATE TABLE material_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    site_id BIGINT,
    item_name VARCHAR(200),
    quantity INT,
    status VARCHAR(20) DEFAULT 'PENDING',
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    processed_by BIGINT,
    remark VARCHAR(500)
);
