-- 修复类型不匹配：DECIMAL(10,7) → DOUBLE PRECISION
-- JPA 实体中使用 Double，PostgreSQL 中 DECIMAL 映射为 NUMERIC 而非 FLOAT

ALTER TABLE sites
    ALTER COLUMN latitude TYPE DOUBLE PRECISION,
    ALTER COLUMN longitude TYPE DOUBLE PRECISION;

ALTER TABLE attendances
    ALTER COLUMN latitude TYPE DOUBLE PRECISION,
    ALTER COLUMN longitude TYPE DOUBLE PRECISION;
