-- V3: Create site_applications table for worker site applications
CREATE TABLE site_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id BIGINT NOT NULL,
    site_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    remark VARCHAR(500),
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP,
    review_remark VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_site_applications_worker FOREIGN KEY (worker_id) REFERENCES users(id),
    CONSTRAINT fk_site_applications_site FOREIGN KEY (site_id) REFERENCES sites(id)
);

CREATE INDEX idx_site_applications_worker ON site_applications(worker_id);
CREATE INDEX idx_site_applications_site ON site_applications(site_id);
CREATE INDEX idx_site_applications_status ON site_applications(status);
